### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found 

### ISSUE THREAD

**Issue by com360** [koral--/android-gif-drawable#107]
Hi,koral:
 this error is ocured on version 1.0.12, I think it load .so file fail,have any solutions ?Thanks!
java.lang.UnsatisfiedLinkError: Native method not found: pl.droidsonroids.gif.GifDrawable.renderFrame:([IJ[I)Zjava.lang.UnsatisfiedLinkError: Native method not found: pl.droidsonroids.gif.GifDrawable.renderFrame:([IJ[I)Z
        at pl.droidsonroids.gif.GifDrawable.renderFrame(Native Method)
        at pl.droidsonroids.gif.GifDrawable.draw(GifDrawable.java:702)
        at android.widget.ImageView.onDraw(ImageView.java:1080)
        at android.view.View.draw(View.java:14615)
        at android.view.View.draw(View.java:14500)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3116)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2953)
        at android.view.View.draw(View.java:14618)
        at android.view.View.draw(View.java:14500)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3116)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2953)
        at android.view.View.draw(View.java:14618)
        at android.view.View.draw(View.java:14500)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3116)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2953)
        at android.view.View.draw(View.java:14498)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3116)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2953)
        at android.view.View.draw(View.java:14498)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3116)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2953)
        at android.view.View.draw(View.java:14618)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2461)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2725)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2638)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2455)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2021)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1081)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6016)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
        at android.view.Choreographer.doCallbacks(Choreographer.java:599)
        at android.view.Choreographer.doFrame(Choreographer.java:559)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5883)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by woojoo666** [comment]
same issue. I'm using Eclipse which doesn't have native Gradle support, so I'm importing the library manually:

 1. Download the source files and import it into eclipse
 2. Move everything inside /java into /src
 3. According to @koral-- 's comment [here](https://github.com/koral--/android-gif-drawable/issues/78#issuecomment-51966908) , download [v1.0.6](https://github.com/koral--/android-gif-drawable/releases/tag/v1.0.6) and copy the /libs folder to the eclipse project

However, when I try to run it I get the issue above. I'm guessing that the libgif.so library files are outdated, but I can't find where to download the recent versions (and don't have an armeabi machine to build them myself)...

**Comment by koral--** [comment]
`.so` files should be taken from the corresponding version of `aar` file, not from `apklib` of 1.0.6. It is mentioned only to see a structure, not to take a content from it.
In other words to include native library files in Eclipse:
1. take `aar` file (the same version as java sources/jar is used)
2. place contents of `jni` folder from `aar` into `libs` folder of project

**Comment by com360** [comment]
I don't use  gradle to compile ，but used maven to build my project. .so files be taken from the version 1.0.12 of arr file.This crash only occur  on some phone by accident.

**Comment by koral--** [comment]
`UnsatisfiedLinkError: Native method not found pl.droidsonroids.gif.GifDrawable.renderFrame:([IJ[I)Z` means that native library is loaded (if it wouldn't then `UnsatisfiedLinkError: Couldn't load gif...` will be thrown) but does not contain mentioned method. So either .so file is broken or came from different library version. If problem occurs randomly on specific devices (but on another ones it doesn't) it might be a bug in ROM of the device (see #17).
There is nothing I can do I think.

**Comment by IgorGanapolsky** [comment]
@koral--  I am facing a similar error.  What do you mean 
> .so file is broken
How can it be broken?  It works in my other project from which I copied it.

**Comment by koral--** [comment]
As broken I meant corrupted.
JNI functions signatures in `.so` file have to match native method signatures in java class. If `.so` file comes from different library version than java classes then native method call will fail with error specified in this issue title.
In this particular case:
- signature `GifDrawable.renderFrame:([IJ[I)Z:`
- version 1.0.12
it seems that `.so` file comes from newer version. 1.0.12 was the last one containing that native method.

If you copied `.so` file only to another project then it may or may not work depending on whether native methods signatures match or not.
