### ISSUE TITLE
v1.1.2 fails on HTC One (M8)

### ISSUE THREAD

**Issue by andreyice** [koral--/android-gif-drawable#126]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@427b7ed
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:600)
at pl.droidsonroids.gif.GifDrawable.void draw(android.graphics.Canvas)(GifDrawable.java:682)
at android.widget.ImageView.onDraw(ImageView.java:1227)

Possible solution:
change
                    canvas.drawBitmap(mBuffer, mSrcRect, mDstRect, mPaint);

to
            try {
                if (!mBuffer.isRecycled()) {
                    canvas.drawBitmap(mBuffer, mSrcRect, mDstRect, mPaint);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

**Comment by koral--** [comment]
Only way to get `Bitmap` recycled is to call `GifDrawable#recycle()` and then try to draw it. There is no other code in library which recycles the Bitmap.
Did you entered that state in some other way? Or did you call `recycle()` and you expect that attempt to draw recycled drawable should be ignored?

Behavior here is now the same as in [BitmapDrawable](http://developer.android.com/reference/android/graphics/drawable/BitmapDrawable.html), it is not checking on every draw attempt if underlying `Bitmap` is recycled but throws the same exception.

**Comment by koral--** [comment]
Closing due to inactivity. Issue can be reopened if more info is provided.
