### ISSUE TITLE
v1.1.2 NullPointerException - reported by Crashlytics

### ISSUE THREAD

**Issue by apkelly** [koral--/android-gif-drawable#131]
Device: Samsung GT-I9505
Android: 4.4.2

java.lang.NullPointerException
       at android.view.View.unscheduleDrawable(View.java:15842)
       at android.graphics.drawable.Drawable.unscheduleSelf(Drawable.java:409)
       at pl.droidsonroids.gif.GifDrawable$2.doWork(GifDrawable.java:102)
       at pl.droidsonroids.gif.GifDrawable$SafeRunnable.run(GifDrawable.java:50)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by koral--** [comment]
Thanks.
