### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by xp8812** [koral--/android-gif-drawable#145]
java.lang.ExceptionInInitializerError
	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:108)

hi koral,please look into this.

**Comment by koral--** [comment]
Please post complete stacktrace.

**Comment by xp8812** [comment]
java.lang.ExceptionInInitializerError
	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:108)
	at com.cu.client.model.cache.CUFileCacheManager.getGifPicFromLocal(CUFileCacheManager.java:218)
	at com.cu.client.model.cache.CUFileCacheManager.access$2(CUFileCacheManager.java:213)
	at com.cu.client.model.cache.CUFileCacheManager$3.run(CUFileCacheManager.java:196)
	at com.cu.client.model.cache.CUFileCacheManager$3.run(CUFileCacheManager.java:1)
	at com.cu.client.model.cache.CUFileCacheManager$4$1.run(CUFileCacheManager.java:279)
	at com.cu.client.model.cache.CUFileCacheManager$4$1.run(CUFileCacheManager.java:1)
	at com.cu.client.sdk.handler.CUFileHandler$1.run(CUFileHandler.java:218)
	at com.cu.client.sdk.handler.CUFileHandler$1.run(CUFileHandler.java:1)
	at com.cu.client.sdk.handler.CUFileHandler$2.run(CUFileHandler.java:278)
	at com.cu.client.sdk.handler.CUFileHandler$2.run(CUFileHandler.java:1)
	at com.cu.client.sdk.net.McpReader$3.run(McpReader.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load gif: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:535)
	at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:39)
	... 15 more
java.lang.UnsatisfiedLinkError: Couldn't load gif: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:535)
	at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:39)
	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:108)
	at com.cu.client.model.cache.CUFileCacheManager.getGifPicFromLocal(CUFileCacheManager.java:218)
	at com.cu.client.model.cache.CUFileCacheManager.access$2(CUFileCacheManager.java:213)
	at com.cu.client.model.cache.CUFileCacheManager$3.run(CUFileCacheManager.java:196)
	at com.cu.client.model.cache.CUFileCacheManager$3.run(CUFileCacheManager.java:1)
	at com.cu.client.model.cache.CUFileCacheManager$4$1.run(CUFileCacheManager.java:279)
	at com.cu.client.model.cache.CUFileCacheManager$4$1.run(CUFileCacheManager.java:1)
	at com.cu.client.sdk.handler.CUFileHandler$1.run(CUFileHandler.java:218)
	at com.cu.client.sdk.handler.CUFileHandler$1.run(CUFileHandler.java:1)
	at com.cu.client.sdk.handler.CUFileHandler$2.run(CUFileHandler.java:278)
	at com.cu.client.sdk.handler.CUFileHandler$2.run(CUFileHandler.java:1)
	at com.cu.client.sdk.net.McpReader$3.run(McpReader.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

**Comment by xp8812** [comment]
I,m sorry , this exception is my mistake
