### ISSUE TITLE
java.lang.RuntimeException: bad array lengths

### ISSUE THREAD

**Issue by qluan** [koral--/android-gif-drawable#154]
Caused by: java.lang.RuntimeException: bad array lengths
	at android.os.Parcel.readLongArray(Parcel.java:864)
	at pl.droidsonroids.gif.GifViewSavedState.&lt;init&gt;(GifViewSavedState.java:30)
	at pl.droidsonroids.gif.GifViewSavedState.&lt;init&gt;(GifViewSavedState.java:9)
	at pl.droidsonroids.gif.GifViewSavedState$1.createFromParcel(GifViewSavedState.java:50)
	at pl.droidsonroids.gif.GifViewSavedState$1.createFromParcel(GifViewSavedState.java:47)
	at android.os.Parcel.readParcelable(Parcel.java:2111)
	at android.os.Parcel.readValue(Parcel.java:2020)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2382)
	at android.os.Parcel.readSparseArray(Parcel.java:1742)
	at android.os.Parcel.readValue(Parcel.java:2077)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
	at android.os.Bundle.unparcel(Bundle.java:249)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:883)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1922)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:266)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:122)
	at com.douban.frodo.activity.BaseActivity.onCreate(BaseActivity.java:65)
	at com.douban.frodo.activity.ImageActivity.onCreate(ImageActivity.java:102)
	at android.app.Activity.performCreate(Activity.java:5249)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)

**Comment by koral--** [comment]
Fixed, thanks for the report.
