### ISSUE TITLE
 Could not read input channel file descriptors from parcel

### ISSUE THREAD

**Issue by xh2009cn** [koral--/android-gif-drawable#159]
My Apps use v1.1.2 , somethimes it will crash by java.lang.RuntimeException: Could not read input channel file descriptors from parcel.Is somewhere forget to release which class file descriptor leak?

**Comment by koral--** [comment]
Please append full stacktrace.

**Comment by xh2009cn** [comment]
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
	at com.android.internal.view.InputBindResult.&lt;init&gt;(InputBindResult.java:62)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:102)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:99)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:713)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1173)
	at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1379)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3223)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5014)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by koral--** [comment]
Problem is located outside this library. That is known bug in Android framework: https://code.google.com/p/android/issues/detail?id=32470

**Comment by 741968602** [comment]
i'v no idea ~
