### ISSUE TITLE
Crash while creating GifDrawable(String) with invalid path

### ISSUE THREAD

**Issue by agrajaghh** [koral--/android-gif-drawable#160]
If I create a `GifDrawable` with an invalid path, I'm getting a `NoSuchMethodError`, but I guess a `IOException` should be thrown, no?

````java
try {
	mGifDrawable = new GifDrawable("invalid-path-string");
} catch (IOException e) {	
	Log.e(TAG, Log.getStackTraceString(e));
}
```` 

````
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.test, PID: 28681
    java.lang.NoSuchMethodError: no non-static method "Lpl/droidsonroids/gif/GifIOException;.<init>(I)V"
            at pl.droidsonroids.gif.GifInfoHandle.openFile(Native Method)
            at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:109)
            at org.test.MainActivity.onCreate(MainActivity.java:112)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

````

**Comment by koral--** [comment]
`GifIOException` should be thrown in that case. It looks like you have incorrect proguard configuration and GifIOException constructor has been stripped. Here is correct configuration: https://github.com/koral--/android-gif-drawable#-proguard-configuration
`pl/droidsonroids/gif/GifIOException` `<init>` `(I)V` is a [constructor](https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/GifIOException.java#L26) which should be kept by 1st rule from proguard config: `-keep public class pl.droidsonroids.gif.GifIOException{<init>(int);}`

**Comment by agrajaghh** [comment]
shame on me, thanks for the help!
