### ISSUE TITLE
Canvas: trying to use a recycled bitmap 

### ISSUE THREAD

**Issue by SyllaJay** [koral--/android-gif-drawable#199]
Hi, I got a crash here.

08-20 12:23:51.063  10384-10384/com.. D/AndroidRuntime﹕ Shutting down VM
08-20 12:23:51.063  10384-10384/com.. W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41688ba8)
08-20 12:23:51.103  10384-10384/com.meitu.highchat E/MTLog CrashHandler﹕ Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4368df60
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4368df60
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
            at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
            at pl.droidsonroids.gif.GifDrawable.draw(GifDrawable.java:700)
            at android.widget.ImageView.onDraw(ImageView.java:1037)
            at android.view.View.draw(View.java:14465)
            at android.view.View.getDisplayList(View.java:13362)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14468)
            at android.view.View.getDisplayList(View.java:13362)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13357)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13357)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14468)
            at android.view.View.getDisplayList(View.java:13362)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14468)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at android.view.View.getDisplayList(View.java:13362)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13357)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.View.draw(View.java:14182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14468)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
            at android.view.View.getDisplayList(View.java:13362)
            at android.view.View.getDisplayList(View.java:13404)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:78
08-20 12:23:51.113  10384-10384/com.. E/AndroidRuntime﹕ FATAL EXCEPTION: main

**Comment by koral--** [comment]
Please post your code. That exception may be thrown if you are recycling `GifDrawable` which is still visible.

**Comment by SyllaJay** [comment]
There's too much logic code. 
But, it is a ListView contains GifImageView, changing GifImageView visibility frequently.
Is it possible that this exception is caused by ListView recycling?

**Comment by koral--** [comment]
No, unless you are calling `GifDrawable#recycle()`.
The only possible cause of that Exception is that your code calls `GifDrawable#recycle()` (excluding direct access to package-private fields or broken ROMs) and after that drawable is tried to be drawn.
Code in library does not call `#recycle()` anywhere.

**Comment by SyllaJay** [comment]
I do call #recycle() manually.
Is it necessary to call #recycle() manually when the GifDrawable of the GifImageView needs to be replaced?

It is my code bellow.

public class GifView extends GifImageVIew {
.......

public void displayGif(String gif) {
        try {
            recyclePotential();
            GifDrawable drawable = new GifDrawable(gif);
            this.setImageDrawable(drawable);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void recyclePotential() {
        GifDrawable drawable = (GifDrawable) getDrawable();
        if (drawable != null) {
            drawable.recycle();
            drawable = null;
        }
    }
......
}

**Comment by koral--** [comment]
It is not necessary to call `recycle()`. It is mainly useful on API levels < 11 when there is a lot of memory consumed by bitmaps. See this official documentation for more info: https://developer.android.com/training/displaying-bitmaps/manage-memory.html#recycle
`GifDrawable` uses `Bitmap` to store pixels which are later drawn. So the same rules as for bitmaps apply.
If you are calling `recycle()` you must ensure yourself that recycled drawable will not be used anymore (it must not be associated with any `View` etc.).
