### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by RubenGees** [koral--/android-gif-drawable#205]
I have a lib with your lib in it. When I use my lib in a project I get the following crash:
```java
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.GifIOException" on path: DexPathList[[zip file "/data/app/com.rubengees.introductionsample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.rubengees.introductionsample-1/lib/arm, /data/app/com.rubengees.introductionsample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at pl.droidsonroids.gif.GifInfoHandle.openFd(Native Method)
            at pl.droidsonroids.gif.GifInfoHandle.a(Unknown Source)
            at pl.droidsonroids.gif.b.<init>(Unknown Source)
            at pl.droidsonroids.gif.b.<init>(Unknown Source)
            at pl.droidsonroids.gif.h.a(Unknown Source)
            at pl.droidsonroids.gif.GifImageView.setImageResource(Unknown Source)
```
I tried both `'proguard-android-optimize.txt` and `'proguard-android.txt`, not working.

**Comment by RubenGees** [comment]
I am terribly sorry, I didn't use the most recent version... It is working now.
