### ISSUE TITLE
Crashing in GifViewUtils 

### ISSUE THREAD

**Issue by kovidkapoor** [koral--/android-gif-drawable#220]
Hi,

We're using this library to animate the loading icon for our Android app, and we faced this crash after the latest updated. I wish I could interpret the error better, but I'm posting the error details below

Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.holidify.andorid.app.holidify/com.holidify.andorid.app.holidify.ui.SplashActivity}: android.view.InflateException: Binary XML file line #15: Error inflating class pl.droidsonroids.gif.GifTextView.

**Comment by koral--** [comment]
Please post complete stacktrace.

**Comment by kovidkapoor** [comment]
java.lang.RuntimeException: Unable to resume activity {com.holidify.andorid.app.holidify/com.holidify.andorid.app.holidify.ui.SplashActivity}: android.view.InflateException: Binary XML file line #15: Error inflating class pl.droidsonroids.gif.GifTextView
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2989)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3018)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class pl.droidsonroids.gif.GifTextView
       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:342)
       at android.app.Dialog.setContentView(Dialog.java:488)
       at com.holidify.andorid.app.holidify.widgets.CustomProgressDialog.onCreate(CustomProgressDialog.java:28)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:372)
       at android.app.Dialog.show(Dialog.java:273)
       at com.holidify.andorid.app.holidify.widgets.CustomProgressDialog.show(CustomProgressDialog.java:33)
       at com.holidify.andorid.app.holidify.ui.SplashActivity.showProgressDialog(SplashActivity.java:712)
       at com.holidify.andorid.app.holidify.ui.SplashActivity.onResume(SplashActivity.java:166)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
       at android.app.Activity.performResume(Activity.java:5429)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3018)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:342)
       at android.app.Dialog.setContentView(Dialog.java:488)
       at com.holidify.andorid.app.holidify.widgets.CustomProgressDialog.onCreate(CustomProgressDialog.java:28)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:372)
       at android.app.Dialog.show(Dialog.java:273)
       at com.holidify.andorid.app.holidify.widgets.CustomProgressDialog.show(CustomProgressDialog.java:33)
       at com.holidify.andorid.app.holidify.ui.SplashActivity.showProgressDialog(SplashActivity.java:712)
       at com.holidify.andorid.app.holidify.ui.SplashActivity.onResume(SplashActivity.java:166)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
       at android.app.Activity.performResume(Activity.java:5429)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3018)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NoClassDefFoundError: pl.droidsonroids.gif.R$styleable
       at pl.droidsonroids.gif.GifViewUtils.isFreezingAnimation(GifViewUtils.java:71)
       at pl.droidsonroids.gif.GifTextView.init(GifTextView.java:112)
       at pl.droidsonroids.gif.GifTextView.<init>(GifTextView.java:44)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:342)
       at android.app.Dialog.setContentView(Dialog.java:488)
       at com.holidify.andorid.app.holidify.widgets.CustomProgressDialog.onCreate(CustomProgressDialog.java:28)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:372)
       at android.app.Dialog.show(Dialog.java:273)
       at com.holidify.andorid.app.holidify.widgets.CustomProgressDialog.show(CustomProgressDialog.java:33)
       at com.holidify.andorid.app.holidify.ui.SplashActivity.showProgressDialog(SplashActivity.java:712)
       at com.holidify.andorid.app.holidify.ui.SplashActivity.onResume(SplashActivity.java:166)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
       at android.app.Activity.performResume(Activity.java:5429)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3018)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by koral--** [comment]
`Caused by: java.lang.NoClassDefFoundError: pl.droidsonroids.gif.R$styleable` it looks like you are using Eclipse or have copied only java sources without XML files. See https://github.com/koral--/android-gif-drawable-eclipse-sample
