### ISSUE TITLE
Gif Not working

### ISSUE THREAD

**Issue by hareesh145** [koral--/android-gif-drawable#253]
Hi,
When i am running gif animation working properly but once i generated the signed apk with progaurd or Dexguard gif not working and i placed the following lines
-keep public class pl.droidsonroids.gif.GifIOException{<init>(int);}
-keep class pl.droidsonroids.gif.GifInfoHandle{<init>(long,int,int,int);}

But still araising the issue please help me

**Comment by koral--** [comment]
Please post stacktrace/logcat output and or code snippet.

**Comment by hareesh145** [comment]
Hi following logcat :-

android.content.res.Resources$NotFoundException: File from drawable resource ID #0x7f020082
at android.content.res.Resources.openRawResourceFd(Resources.java:1130)
 at pl.droidsonroids.gif.GifDrawable.<init>(:95)
  at com.mypackage.SplashScreen.onCreate(:89)
 at android.app.Activity.performCreate(Activity.java:5411)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
   at android.app.ActivityThread.access$800(ActivityThread.java:139)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
     at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:149)
    at android.app.ActivityThread.main(ActivityThread.java:5268)
     at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
 at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
     at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
     at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:429)
     at android.content.res.Resources.openRawResourceFd(Resources.java:1127)

**Comment by koral--** [comment]
The reason is: `This file can not be opened as a file descriptor; it is probably compressed`.
By default if file has `.gif` extension it should not be compressed by aapt.
Does file which you try to load has `.gif` extension? If not then you can either add it or exclude it from compression like that (in `build.gradle`):
```
android {
    aaptOptions {
        noCompress "<your file extension>"
    }
}
```
If that is not a case (your file has `.gif` extension), could  you attach it here?

**Comment by manoj99** [comment]
i have used gif-drawable in listview.when i am clicking on it to navigate another activity and return back then gif have getting stuck.need suggestion for this.

**Comment by koral--** [comment]
@manoj99 please post your code in separate issue.

**Comment by koral--** [comment]
Closing due to inactivity, may be reopened if more info is provided.
