### ISSUE TITLE
RuntimeException stopping decoding thread in GifTexImage2D

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#275]
I am currently stopping / starting decoder thread in GifTexImage2D based on visibility of the texture to save CPU cycles (even if a proper pause method would be much better as per #273 comment), randomly i get this exception:

`E/System: java.lang.RuntimeException: Slurp mutex destroy failed Success
                                                                          at pl.droidsonroids.gif.GifInfoHandle.free(Native Method)
                                                                          at pl.droidsonroids.gif.GifInfoHandle.recycle(GifInfoHandle.java:155)
                                                                          at pl.droidsonroids.gif.GifInfoHandle.finalize(GifInfoHandle.java:243)
                                                                          at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                          at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by koral--** [comment]
Fixed, thanks.
BTW, this issue could only happen if `GifTexImage2D` was finalized without prior releasing. It is better to explicitly call `GifTexImage2D#release()` and not rely on finalizer (finalization may never occur).

**Comment by frmz** [comment]
Yeah i also realized that after checking the JNI source, thanks :)
