### ISSUE TITLE
GifTexImage2D.recycle() should not call stopDecoderThread if thread is not running

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#276]
I was testing the render frame GL call and i found that there is no proper way to free up resources without getting this error IF decoding thread is not in use (so when rendering on a per frame basis)

`java.lang.RuntimeException: Could not write to eventfd Bad file descriptor
                                                                                          at pl.droidsonroids.gif.GifInfoHandle.stopDecoderThread(Native Method)
                                                                                          at pl.droidsonroids.gif.GifInfoHandle.stopDecoderThread(GifInfoHandle.java:301)
                                                                                          at pl.droidsonroids.gif.GifTexImage2D.stopDecoderThread(GifTexImage2D.java:89)
                                                                                          at pl.droidsonroids.gif.GifTexImage2D.recycle(GifTexImage2D.java:96)`

**Comment by koral--** [comment]
Fixed, thanks.
