### ISSUE TITLE
Caused by: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by kaka2009** [koral--/android-gif-drawable#283]
Caused by: java.lang.ExceptionInInitializerError
	at pl.droidsonroids.gif.GifDrawable.<init>(Unknown Source)
	at pl.droidsonroids.gif.GifDrawable.<init>(Unknown Source)
	at pl.droidsonroids.gif.GifViewUtils.setResource(Unknown Source)
	at pl.droidsonroids.gif.GifViewUtils.getResourceId(Unknown Source)
	at pl.droidsonroids.gif.GifViewUtils.initImageView(Unknown Source)
	at pl.droidsonroids.gif.GifImageView.<init>(Unknown Source)
	at com.qihoo.video.widget.MatrixImageView.<init>(Unknown Source)
	at com.qihoo.video.widget.MatrixImageView.<init>(Unknown Source)
	... 81 more
Caused by: java.lang.IncompatibleClassChangeError: interface not implemented
	at pl.droidsonroids.gif.ReLinker.closeSilently(Unknown Source)
	at pl.droidsonroids.gif.ReLinker.unpackLibrary(Unknown Source)
	at pl.droidsonroids.gif.ReLinker.loadLibrary(Unknown Source)
	at pl.droidsonroids.gif.LibraryLoader.loadLibrary(Unknown Source)
	at pl.droidsonroids.gif.GifInfoHandle.<clinit>(Unknown Source)
	... 89 more

**Comment by koral--** [comment]
This has been fixed in #244, please use the latest library version.

**Comment by ankittest30** [comment]
Still facing this problem on build tool version 25

**Comment by koral--** [comment]
Build tools version should have no meaning here.
Which library version are you using?
