### ISSUE TITLE
Android 6.0 crash

### ISSUE THREAD

**Issue by Revenge94** [koral--/android-gif-drawable#302]
FATAL EXCEPTION: main
                                                                                  Process: PID: 10615
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{main.SplashActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                      at main.SplashActivity.onCreate(SplashActivity.java:20)
                                                                                      at android.app.Activity.performCreate(Activity.java:6237)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                   Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                      at main.SplashActivity.onCreate(SplashActivity.java:20) 
                                                                                      at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                      at main.SplashActivity.onCreate(SplashActivity.java:20) 
                                                                                      at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                   Caused by: java.lang.OutOfMemoryError: Failed to allocate a 134374476 byte allocation with 1048576 free bytes and 95MB until OOM
                                                                                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                      at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                                      at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
                                                                                      at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
                                                                                      at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
                                                                                      at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
                                                                                      at android.content.res.Resources.loadDrawable(Resources.java:2540)
                                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
                                                                                      at android.widget.ImageView.<init>(ImageView.java:152)
                                                                                      at android.widget.ImageView.<init>(ImageView.java:140)
                                                                                      at android.widget.ImageView.<init>(ImageView.java:136)
                                                                                      at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:40)
                                                                                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                      at main.SplashActivity.onCreate(SplashActivity.java:20) 
                                                                                      at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Revenge94** [comment]
IS there another way than add  android:largeHeap="true" into application tag in Android manifest.xml

**Comment by koral--** [comment]
If you are loading a lot of GIFs then you can reuse old `GifDrawables`. If your GIFs are huge you can downsample them.
Both options are available in `GifDrawableBuilder`.
