### ISSUE TITLE
setImageResource() crash on Android N

### ISSUE THREAD

**Issue by Parseus** [koral--/android-gif-drawable#317]
android-gif-drawable crashes on Nexus 9 with the newest Android N Preview while trying to use setImageResource() with the following stacktrace:

> 07-15 11:12:18.417 25787-25787/com.explaineverything.explaineverything E/art: No implementation found for boolean pl.droidsonroids.gif.GifInfoHandle.isOpaque(long) (tried Java_pl_droidsonroids_gif_GifInfoHandle_isOpaque and Java_pl_droidsonroids_gif_GifInfoHandle_isOpaque__J)
07-15 11:12:18.421 25787-25787/com.explaineverything.explaineverything E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: com.explaineverything.explaineverything, PID: 25787
                                                                                         java.lang.UnsatisfiedLinkError: No implementation found for boolean pl.droidsonroids.gif.GifInfoHandle.isOpaque(long) (tried Java_pl_droidsonroids_gif_GifInfoHandle_isOpaque and Java_pl_droidsonroids_gif_GifInfoHandle_isOpaque__J)
                                                                                             at pl.droidsonroids.gif.GifInfoHandle.isOpaque(Native Method)
                                                                                             at pl.droidsonroids.gif.GifInfoHandle.isOpaque(GifInfoHandle.java:301)
                                                                                             at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:235)
                                                                                             at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161)
                                                                                             at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96)
                                                                                             at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:53)
                                                                                             at pl.droidsonroids.gif.GifImageView.setImageResource(GifImageView.java:101)
                                                                                             at com.explaineverything.core.fragments.DiscoverFragment.loadAnimation(DiscoverFragment.java:98)
                                                                                             at com.explaineverything.core.fragments.DiscoverFragment.onCreateView(DiscoverFragment.java:85)
                                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                                             at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6044)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

This happens on 1.1.17. Older versions work fine.

**Comment by koral--** [comment]
I have currently no such device but I could not reproduce this issue with latest N preview on emulator neither on Nexus 5X with API 23 (which has the same ABI as Nexus 9).
All `.so` files published to maven central contains symbol `Java_pl_droidsonroids_gif_GifInfoHandle_isOpaque` which is present since 1.1.16.

This may be some kind of packaging problem like in #107.

Are you including library as gradle dependency or compiling from source on your own? Does problem persist after clean build and/or clean app install (not upgrade from previous version)?

**Comment by koral--** [comment]
Closed due to inactivity, may be reopened if more info is provided.
