### ISSUE TITLE
 Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by TheMelody** [koral--/android-gif-drawable#324]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@8476b5a
                                                                           at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                                                           at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
                                                                           at pl.droidsonroids.gif.GifDrawable.draw(GifDrawable.java:726)
                                                                           at android.view.View.getDrawableRenderNode(View.java:16427)
                                                                           at android.view.View.drawBackground(View.java:16363)
                                                                           at android.view.View.draw(View.java:16175)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15180)

**Comment by koral--** [comment]
Are you calling `Bitmap#recycle()` somewhere in your code? See https://github.com/koral--/android-gif-drawable/issues/316#issuecomment-231595088.

**Comment by velsans** [comment]
thank u its working
