### ISSUE TITLE
OutOfMemoryError: Failed to allocate a 2908172 byte allocation with 2775936 free bytes and 2MB until OOM

### ISSUE THREAD

**Issue by lekenny** [koral--/android-gif-drawable#327]
`at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:884)
	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:230)
	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:125)`

this is my code

`try {
            gifFromAfd = new GifDrawable(path);
        } catch (IOException e) {
            e.printStackTrace();
        }`

**Comment by koral--** [comment]
See #326
