### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zhumingwei** [koral--/android-gif-drawable#334]
I just add  "compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.14'" ,
then when i run app get back an Error Like this:

ava.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/mobi.yellow.battery-2/base.apk"],nativeLibraryDirectories=[/data/app/mobi.yellow.battery-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libandrll.so"
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:378)
                                                                              at java.lang.System.loadLibrary(System.java:998)
                                                                              at mobi.andrutil.autolog.NativeDaemon22.<clinit>(SourceFile:20)
                                                                              at com.a.ll.l.run(SourceFile:85)

**Comment by zhumingwei** [comment]
I found the reason of this problem：
because i have an other mudule that has a confilict  with this

**Comment by koral--** [comment]
Yeah, `libandrll.so` is not a part of this library.
