### ISSUE TITLE
Error inflating class pl.droidsonroids.gif.GifImageView

### ISSUE THREAD

**Issue by talmmi** [koral--/android-gif-drawable#354]
I'm using an android phone 4.1 (sdk 16) 
Before its working fine but testing it today, I'm having an error 

android.view.InflateException: Binary XML file line #23: Error inflating class pl.droidsonroids.gif.GifImageView

In my dependencies I put 

     compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.2'

and In my layout i call it like this 

    <pl.droidsonroids.gif.GifImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/myImage"
        />

But the error keeps on pointing on my setContentView(R.layout.mainactivity); in my onCreate where I initialize my GifImageView like this 

                        GifImageView gifImageView = (GifImageView) findViewById(R.id.myImage);
			String ext = imageTitle.substring(imageTitle.length() - 4).toLowerCase().trim();

			if(ext.equals(".gif")){
				if (Utils.isUsingExternalStorage(context)) {
					gifFile = new File(context.getExternalFilesDir(null)
							.getAbsolutePath(), imageTitle);
				} else {
					gifFile = new File(context.getFilesDir().getAbsolutePath(), imageTitle);
				}

				try {
					gifFromPath = new GifDrawable(gifFile);
				} catch (IOException e) {
					e.printStackTrace();
				}

				gifImageView.setImageDrawable(gifFromPath);

			}else{
				gifImageView.setImageBitmap(Utils.getBitmapImagefromStorage(
						context, imageTitle));
			}

**Comment by koral--** [comment]
Please attach complete stacktrace. Are you using multidex?

**Comment by talmmi** [comment]
Yes, I'm using multidex
 
    defaultConfig {
           multiDexEnabled true
     }

     dependencies {
           compile 'com.android.support:multidex:1.0.0'
            compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.2'
     }

**Comment by koral--** [comment]
See recent issue with multidex: https://github.com/koral--/android-gif-drawable/issues/349#issuecomment-251146416

If you have followed all the steps from https://developer.android.com/studio/build/multidex.html#mdex-gradle and issue is still present please attach complete stacktrace.

**Comment by talmmi** [comment]
Its working fine now thank you so much!

**Comment by utsavdotpro** [comment]
Hi @koral-- , I am not using multidex but still getting this error with release builds on only a few devices.

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.isolpro.sghl/com.isolpro.sghl.activities.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class pl.droidsonroids.gif.GifImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2520)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2600)
       at android.app.ActivityThread.access$800(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5622)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

> Caused by android.view.InflateException: Binary XML file line #12: Error inflating class pl.droidsonroids.gif.GifImageView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at androidx.appcompat.view.WindowCallbackWrapper.getWrapped(WindowCallbackWrapper.java)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java)
       at com.isolpro.sghl.custom.Activity.onCreate(Activity.java)
       at com.isolpro.sghl.activities.MainActivity.onCreate(MainActivity.java:2)
       at android.app.Activity.performCreate(Activity.java:6100)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2600)
       at android.app.ActivityThread.access$800(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5622)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by koral--** [comment]
@u-barnwal please create a separate ticket with a complete sample reproducing your issue
