### ISSUE TITLE
new GifDrawable() throw Exception

### ISSUE THREAD

**Issue by max8888888** [koral--/android-gif-drawable#427]
My code:
```
final String imageUrl = "http://img10.3lian.com/edu201302/photoshop/p105/201212/c04492853f8f192d03405c4a5213639c.gif";
        AsyncHttpClient client = new AsyncHttpClient();
        client.get(mContext, imageUrl, new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                try {
                    GifDrawable drawable = new GifDrawable(responseBody);
                    imageView.setImageDrawable(drawable);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
            }
        });
```
The new Gifdrawable(responseBody) will throw exception:
java.lang.NoSuchMethodError: no non-static method "Lpl/droidsonroids/gif/GifInfoHandle;.<init>(JIII)V"
at pl.droidsonroids.gif.GifInfoHandle.openFile(Native Method)
at pl.droidsonroids.gif.GifInfoHandle.<init>(GifInfoHandle.java:49)
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:123)
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:134)

My god! where the error in my code ?
Please help!

**Comment by max8888888** [comment]
GifDrawable drawable = new GifDrawable(getResources(), R.raw.test);

I try to use the resource image. got the same error......

**Comment by koral--** [comment]
That error may be thrown if native library version (`.so` file) is inconsistent with Java library version.
How do you do depend on android-gif-drawable. Are you using Gradle dependency?

**Comment by max8888888** [comment]
I'm use Android studio 2.3.3
gradle version is 3.5
My PC setup java version is "1.8.0_40"
```
**app  build.gradle file is :**
android {
    compileSdkVersion 25
    buildToolsVersion '25.0.3'
    useLibrary 'org.apache.http.legacy'

    dexOptions {
        javaMaxHeapSize "4g"
    }

    defaultConfig {
        applicationId "com.jianzhibao.ka.personal"
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 65
        versionName "4.9.2"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi"
        }
    }

    signingConfigs {
        debug {
            storeFile file('D:/android/ide/studio-sdk/.android/debug.keystore')
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.google.android.gms:play-services-appindexing:9.8.0'
    compile 'com.github.barteksc:android-pdf-viewer:2.4.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:design:25.3.1'
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.7'
    compile project(':expandabletextview')
}
------
**project build.gradle file is:**
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```
Do you need other infomation?

**Comment by max8888888** [comment]
I found, I have not import any .so files.  Where to download ?

**Comment by koral--** [comment]
`.so` should be included if you use `compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.7'` dependency.
Is it reproducible after clean build (Build->Clean project in Android Studio) and clean installation (uninstall an app if it is already installed on device)?

**Comment by max8888888** [comment]
It worked!  I did as you said(clean, and rebuild, and uninstall the app...). 
God knows what happened~   May be the Android Studio was ill  :)
Thank you again! 
Thank you very much!
