### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: no method with name='<init>' signature='(I)V' in class Lpl/droidsonroids/gif/GifIOException

### ISSUE THREAD

**Issue by xiaoxiyang09** [koral--/android-gif-drawable#484]
Thanks for any help! 
When i use GifImageView in my project, in some real devices, it crashes.
My  minSdkVersion is 14,and  i has 'compile(name: 'android-gif-drawable-1.2.8', ext: 'aar')' in my build.gradle.
Here is all the error information:
java.lang.RuntimeException: Unable to resume activity {com.ea.android/com.ea.android.cen.activity.FoActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class pl.droidsonroids.gif.GifImageView 
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2798) 
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2262) 
at android.app.ActivityThread.access$800(ActivityThread.java:143) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5120) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class pl.droidsonroids.gif.GifImageView 
at android.view.LayoutInflater.createView(LayoutInflater.java:620) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
at com.ea.android.cen.util.a$a.a(SourceFile:331) 
at com.ea.android.fu.cen.util.a$a.<init>(SourceFile:326) 
at com.ea.android.fu.cen.util.a$a.<init>(SourceFile:320) 
at com.ea.android.fu.cen.util.a$a.<init>(SourceFile:316) 
at com.ea.android.fu.cen.util.a.b(SourceFile:294) 
at com.ea.android.fu.cen.util.a.a(SourceFile:80) 
at com.ea.android.fu.cen.activity.FoFragment.j(SourceFile:366) 
at com.ea.android.fu.cen.activity.FoFragment.a(SourceFile:357) 
at com.ea.android.fu.cen.activity.FoFragment.onResume(SourceFile:562) 
at android.support.v4.app.Fragment.performResume(SourceFile:2238) at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1346) at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1528) at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1595) at android.support.v4.app.FragmentManagerImpl.dispatchResume(SourceFile:2914) at android.support.v4.app.FragmentController.dispatchResume(SourceFile:223) at android.support.v4.app.FragmentActivity.onResumeFragments(SourceFile:509) at android.support.v4.app.FragmentActivity.onPostResume(SourceFile:498) 
at android.support.v7.app.AppCompatActivity.onPostResume(SourceFile:172) 
at android.app.Activity.performResume(Activity.java:5412) 
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2788)
... 12 more Caused by: java.lang.reflect.InvocationTargetException 
at java.lang.reflect.Constructor.constructNative(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
... 37 more Caused by: java.lang.NoSuchMethodError: no method with name='<init>' signature='(I)V' in class Lpl/droidsonroids/gif/GifIOException; 
at pl.droidsonroids.gif.GifInfoHandle.openFd(Native Method) 
at pl.droidsonroids.gif.GifInfoHandle.<init>(SourceFile:58) 
at pl.droidsonroids.gif.b.<init>(SourceFile:160) 
at pl.droidsonroids.gif.b.<init>(SourceFile:95) 
at pl.droidsonroids.gif.d.a(SourceFile:52) 
at pl.droidsonroids.gif.d$a.a(SourceFile:137) 
at pl.droidsonroids.gif.d$a.<init>(SourceFile:123) 
at pl.droidsonroids.gif.d.a(SourceFile:30) 
at pl.droidsonro
----------------------------------------------------------------------------------------------
Waiting for replying! Thanks!

**Comment by koral--** [comment]
If don't use gradle, you should add proguard rule from this file: https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/consumer-proguard-rules.pro to your proguard config.

**Comment by xiaoxiyang09** [comment]
Thanks! INow i add  '-dontwarn android-gif-drawable-1.2.8.**    -keep public class android-gif-drawable-1.2.8.** {*;} ' to my proguard config.I haven't got result now,it may cost some time.However according to 'Caused by: java.lang.NoSuchMethodError: no method with name='' signature='(I)V' ',it means No method like 'private GifIOException(int errorCode) {this.reason = GifError.fromCode(errorCode);}' was found in class GifIOException.I  checked the source code ,and it doesn't have such a method 'private GifIOException(int errorCode) {this.reason = GifError.fromCode(errorCode);}' .But it has 'private GifIOException(int errorCode, String errnoMessage) {
        this.reason = GifError.fromCode(errorCode);
        this.mErrnoMessage = errnoMessage;
    }' in it. And your advice is '-keep public class pl.droidsonroids.gif.GifIOException{<init>(int, java.lang.String);}',It seems that your advice matches  the source code,but not matches my error information.That's what makes me confused. Was i wrong somewhere? Again,thanks!

**Comment by koral--** [comment]
Sorry, I haven't spotted that difference.
`no method with name='' signature='(I)V'` it seems that either text is malformed.
Here is the code: 
https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/src/main/c/exception.c#L62
`(*env)->GetMethodID(env, exClass, "<init>", "(ILjava/lang/String;)V");`

BTW
`-dontwarn android-gif-drawable-1.2.8.** -keep public class android-gif-drawable-1.2.8.** {*;}`
 is not a valid proguard rule.

Could you confirm that stacktrace in your 1st post is in original form?

**Comment by xiaoxiyang09** [comment]
I'm so sorry! I was careless and thoughtless.
Firstly,thanks for pointing out '-dontwarn android-gif-drawable-1.2.8.** -keep public class android-gif-drawable-1.2.8.** {*;}  is not a valid proguard rule'. Now it's '-dontwarn pl.droidsonroids.gif.**  -keep public class pl.droidsonroids.gif.** {*;} '.

On the other hand, 1st post is not in original form, i don't know why it has been like this, i just copy.
The key line ' no method with name='' signature='(I)V' ' both in 1st post and 2nd  ,is not same as the real error.Actually,the key line should be 'Caused by: java.lang.NoSuchMethodError: no method with name='\<init>' signature='(I)V' in class Lpl/droidsonroids/gif/GifIOException'.That's original form.Just the same as title of the issue.

**Comment by koral--** [comment]
OK, this message means that native library (`.so` file) is in the old version, some before that change: https://github.com/koral--/android-gif-drawable/commit/05b046025020309f56a11d9fcd71dc166683a1bd#diff-e2ae76aa4f4e8067554732124949c769
Similar issue has been reported here: https://github.com/koral--/android-gif-drawable/issues/427#issuecomment-317694502 and clean build resolved it.

**Comment by koral--** [comment]
Closing due to inactivity.
