### ISSUE TITLE
Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file

### ISSUE THREAD

**Issue by chengxingen** [koral--/android-gif-drawable#494]
I got an error. 
I use GifImageView in my project like this: 
 xml: 
   <pl.droidsonroids.gif.GifImageView
        android:id="@+id/iv_img"
        android:layout_width="@dimen/dp45"
        android:layout_height="@dimen/dp45"
        android:scaleType="centerCrop"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="@dimen/dp5"
        />
  
code: 
GifDrawable gifDrawable = new GifDrawable(imageUrl());
                holder.img.setImageDrawable(gifDrawable);

but I got an error:
java.lang.ExceptionInInitializerError
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:160)
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:95)
at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:52)
at pl.droidsonroids.gif.GifImageView.setImageResource(GifImageView.java:101)

and

Caused by: java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file
at pl.droidsonroids.gif.ReLinker.unpackLibrary(ReLinker.java:101)
at pl.droidsonroids.gif.ReLinker.loadLibrary(ReLinker.java:58)
at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:21)
                                                                                    	... 87 more

Please help, thank you;

**Comment by chengxingen** [comment]
My project's abiFilters: 

ndk{
            abiFilters "armeabi","armeabi-v7a"
        }

**Comment by hlla** [comment]
@chengxingen Maybe this is the reason,the version 1.2.9 don't have the armeabi
![image](https://user-images.githubusercontent.com/7305059/34189559-fb3162e4-e576-11e7-90db-7041de7c497f.png)

**Comment by chengxingen** [comment]
yeah, that's the reason! 
thank you !!!

**Comment by koral--** [comment]
armeabi target is no longer build by default in current version of NDK, because it is quite old hardware. That's why it is missing in APK.

However, I should include such information in README.

I see there they are still needed so I'll release a new version with armeabi libraries. They can be build if explicitly requested. However, in the near future armeabi support will be completely dropped by NDK.

**Comment by koral--** [comment]
Fixed in version `1.2.10-SNAPSHOT`.

**Comment by SiXuManYan** [comment]
Thank you for this update, it is the perfect solution to my problem

谢谢您的本次更新，它完美的解决了我的问题
