### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c429f0b

### ISSUE THREAD

**Issue by daydream123** [koral--/android-gif-drawable#518]
android-gif-drawable crashed, below is crash logs:

`java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c429f0b
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
	at pl.droidsonroids.gif.GifDrawable.draw(GifDrawable.java:763)
	at android.widget.ImageView.onDraw(ImageView.java:1228)
	at android.view.View.draw(View.java:16201)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1818)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)`

**Comment by koral--** [comment]
It seems that you are recycling the drawable when it is still associated with View.
See https://github.com/koral--/android-gif-drawable/issues/316#issuecomment-231595088.

**Comment by daydream123** [comment]
Thanks, I have found the problem, I called recycle() in my code.
