### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0 

### ISSUE THREAD

**Issue by lizhiwei92** [koral--/android-gif-drawable#528]
```
java.lang.IllegalArgumentException: width and height must be > 0 
at android.graphics.Bitmap.createBitmap(Bitmap.java:638) 
at android.graphics.Bitmap.createBitmap(Bitmap.java:620) 
at pl.droidsonroids.gif.GifDrawable.makeBitmap(GifDrawable.java:244) 
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:229) 
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:148) 
```

**Comment by koral--** [comment]
Could you attach GIF file causing this issue?

**Comment by lizhiwei92** [comment]
sorry about that, it appeared when i run a monkey, i don't know which file caused this problem

**Comment by koral--** [comment]
OK, I'll try to reproduce this.

**Comment by koral--** [comment]
There is no `GifDrawable.makeBitmap` method in the source code in this repo. Where did you get this from?

**Comment by lizhiwei92** [comment]
My project used this lib ：https://github.com/panpf/sketch,
and it's based on android-gif-drawable lib,
lools like this bug belongs to sketch lib. Thank you.
