### ISSUE TITLE
App crashes at launch 

### ISSUE THREAD

**Issue by devxpy** [koral--/android-gif-drawable#569]
Android 7.1.2, nexus 5,    Flutter 0.5.1 

Sorry for new issue, I couldn't figure out what exactly to look for.

build.gradle
```gradle
....
buildscript {
    repositories {
        mavenCentral()
    }
}
allprojects {
    repositories {
        mavenCentral()
    }
}


android {
    compileSdkVersion 28
    ....
    dependencies {
        implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.10'
    }
}
...
```

android/app/src/main/res/drawable/launch_background.xml 
```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <pl.droidsonroids.gif.GifImageView
            android:gravity="center"
            android:src="@mipmap/launch_image"
            android:background="@android:color/black"
            />
    </item>
</layer-list>
```

```
07-13 02:28:28.208   765   790 W WindowManager: Token{fbe5770 ActivityRecord{cc3f5b3 u0 com.pycampers.securepdfviewer/.MainActivity t108}} failed creating starting window
07-13 02:28:28.208   765   790 W WindowManager: android.content.res.Resources$NotFoundException: Drawable com.pycampers.securepdfviewer:drawable/launch_background with resource ID #0x7f020000
07-13 02:28:28.208   765   790 W WindowManager: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f020000
07-13 02:28:28.208   765   790 W WindowManager: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.content.res.Resources.getDrawable(Resources.java:771)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.content.Context.getDrawable(Context.java:525)
07-13 02:28:28.208   765   790 W WindowManager: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2578)
07-13 02:28:28.208   765   790 W WindowManager: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2628)
07-13 02:28:28.208   765   790 W WindowManager: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2047)
07-13 02:28:28.208   765   790 W WindowManager: 	at com.android.server.policy.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:2821)
07-13 02:28:28.208   765   790 W WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:8389)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.os.Looper.loop(Looper.java:154)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-13 02:28:28.208   765   790 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-13 02:28:28.208   765   790 W WindowManager: Caused by: android.view.InflateException: Class not found pl.droidsonroids.gif.GifImageView
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:206)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:128)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:285)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:196)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
07-13 02:28:28.208   765   790 W WindowManager: 	... 12 more
07-13 02:28:28.208   765   790 W WindowManager: Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.GifImageView" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Settings/lib/arm, /system/priv-app/Settings/Settings.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
07-13 02:28:28.208   765   790 W WindowManager: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-13 02:28:28.208   765   790 W WindowManager: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-13 02:28:28.208   765   790 W WindowManager: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-13 02:28:28.208   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:187)
07-13 02:28:28.208   765   790 W WindowManager: 	... 20 more
07-13 02:28:28.221 18235 18235 I art     : Late-enabling -Xcheck:jni
07-13 02:28:28.221   765   776 I ActivityManager: Start proc 18235:com.pycampers.securepdfviewer/u0a148 for activity com.pycampers.securepdfviewer/.MainActivity
07-13 02:28:28.302 18235 18235 D AndroidRuntime: Shutting down VM
07-13 02:28:28.304 18235 18235 E AndroidRuntime: FATAL EXCEPTION: main
07-13 02:28:28.304 18235 18235 E AndroidRuntime: Process: com.pycampers.securepdfviewer, PID: 18235
07-13 02:28:28.304 18235 18235 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pycampers.securepdfviewer/com.pycampers.securepdfviewer.MainActivity}: android.content.res.Resources$NotFoundException: Drawable com.pycampers.securepdfviewer:drawable/launch_background with resource ID #0x7f020000
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.pycampers.securepdfviewer:drawable/launch_background with resource ID #0x7f020000
07-13 02:28:28.304 18235 18235 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f020000
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:771)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:525)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2578)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2628)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2047)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:155)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:86)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.pycampers.securepdfviewer.MainActivity.onCreate(MainActivity.java:11)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6682)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: Caused by: android.view.InflateException: Class is not a Drawable pl.droidsonroids.gif.GifImageView
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:200)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:128)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:285)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:196)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	... 21 more
07-13 02:28:28.304 18235 18235 E AndroidRuntime: Caused by: java.lang.ClassCastException: class pl.droidsonroids.gif.GifImageView cannot be cast to android.graphics.drawable.Drawable
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at java.lang.Class.asSubclass(Class.java:2340)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:187)
07-13 02:28:28.304 18235 18235 E AndroidRuntime: 	... 29 more
07-13 02:28:28.307   765   776 W ActivityManager:   Force finishing activity com.pycampers.securepdfviewer/.MainActivity
```

**Comment by koral--** [comment]
`GifImageView` is a View, it cannot be put inside `launch_background` which is a Drawable.
What exactly do you want to achieve.

**Comment by devxpy** [comment]
I thought this library was for displaying gifs at splash screen, coming from [this](https://stackoverflow.com/a/39871506/7061265) answer on SO.

But now that I look at it, I see that it is a generic View for android.

**Comment by devxpy** [comment]
I tried using `GifDrawable`, but that results in following error:

```
<pl.droidsonroids.gif.GifDrawable
            android:gravity="center"
            android:src="@mipmap/launch_image"
            android:background="@android:color/black"
            />
```


```
07-13 04:47:43.430   765   790 W WindowManager: Token{6223911 ActivityRecord{da3c538 u0 com.pycampers.securepdfviewer/.MainActivity t116}} failed creating starting window
07-13 04:47:43.430   765   790 W WindowManager: android.content.res.Resources$NotFoundException: Drawable com.pycampers.securepdfviewer:drawable/launch_background with resource ID #0x7f020000
07-13 04:47:43.430   765   790 W WindowManager: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f020000
07-13 04:47:43.430   765   790 W WindowManager: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.content.res.Resources.getDrawable(Resources.java:771)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.content.Context.getDrawable(Context.java:525)
07-13 04:47:43.430   765   790 W WindowManager: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2578)
07-13 04:47:43.430   765   790 W WindowManager: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2628)
07-13 04:47:43.430   765   790 W WindowManager: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2047)
07-13 04:47:43.430   765   790 W WindowManager: 	at com.android.server.policy.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:2821)
07-13 04:47:43.430   765   790 W WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:8389)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.os.Looper.loop(Looper.java:154)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-13 04:47:43.430   765   790 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-13 04:47:43.430   765   790 W WindowManager: Caused by: android.view.InflateException: Class not found pl.droidsonroids.gif.GifDrawable
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:206)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:128)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:285)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:196)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
07-13 04:47:43.430   765   790 W WindowManager: 	... 12 more
07-13 04:47:43.430   765   790 W WindowManager: Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.GifDrawable" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/Settings/lib/arm, /system/priv-app/Settings/Settings.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
07-13 04:47:43.430   765   790 W WindowManager: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-13 04:47:43.430   765   790 W WindowManager: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-13 04:47:43.430   765   790 W WindowManager: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-13 04:47:43.430   765   790 W WindowManager: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:187)
07-13 04:47:43.430   765   790 W WindowManager: 	... 20 more
07-13 04:47:43.438   765  1256 I ActivityManager: Start proc 24358:com.pycampers.securepdfviewer/u0a148 for activity com.pycampers.securepdfviewer/.MainActivity
07-13 04:47:43.446 24358 24358 I art     : Late-enabling -Xcheck:jni
07-13 04:47:43.560 24358 24358 D AndroidRuntime: Shutting down VM
07-13 04:47:43.563 24358 24358 E AndroidRuntime: FATAL EXCEPTION: main
07-13 04:47:43.563 24358 24358 E AndroidRuntime: Process: com.pycampers.securepdfviewer, PID: 24358
07-13 04:47:43.563 24358 24358 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pycampers.securepdfviewer/com.pycampers.securepdfviewer.MainActivity}: android.content.res.Resources$NotFoundException: Drawable com.pycampers.securepdfviewer:drawable/launch_background with resource ID #0x7f020000
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.pycampers.securepdfviewer:drawable/launch_background with resource ID #0x7f020000
07-13 04:47:43.563 24358 24358 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f020000
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:771)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:525)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2578)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2628)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2047)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:155)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:86)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.pycampers.securepdfviewer.MainActivity.onCreate(MainActivity.java:11)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6682)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: Caused by: android.view.InflateException: Error inflating class pl.droidsonroids.gif.GifDrawable
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:194)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:128)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:285)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:196)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	... 21 more
07-13 04:47:43.563 24358 24358 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: <init> []
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:2204)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at java.lang.Class.getConstructor(Class.java:1683)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:188)
07-13 04:47:43.563 24358 24358 E AndroidRuntime: 	... 29 more
07-13 04:47:43.566   765   985 W ActivityManager:   Force finishing activity com.pycampers.securepdfviewer/.MainActivity

```

**Comment by koral--** [comment]
Assuming that you have `launch_image.gif` file in your mipmap folder, something like this:
```xml
        <pl.droidsonroids.gif.GifImageView
            android:gravity="center"
            android:src="@mipmap/launch_image"
            android:background="@android:color/black"
            />
```
will work but you need to place it inside layout XML (not drawable).
Look at the sample code: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/res/layout/texture.xml#L32
