### ISSUE TITLE
android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class pl.droidsonroids.gif.GifImageView

### ISSUE THREAD

**Issue by DeepanshuNamdeo** [koral--/android-gif-drawable#627]
I am having problem in release apk 
i am using muiltidex 

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.blancco.diagnostics.cs/com.xcaliber.mobilediagnostic.app.CosmeticConditionTest}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class pl.droidsonroids.gif.GifImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
     Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class pl.droidsonroids.gif.GifImageView
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class pl.droidsonroids.gif.GifImageView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.support.v7.app.AppCompatDelegateImpl.b(Unknown Source)
        at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
        at com.xcaliber.mobilediagnostic.app.CosmeticConditionTest.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6845)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int pl.droidsonroids.gif.n.a(java.io.FileDescriptor) (tried Java_pl_droidsonroids_gif_n_a and Java_pl_droidsonroids_gif_n_a__Ljava_io_FileDescriptor_2)
        at pl.droidsonroids.gif.n.a(Native Method)
        at pl.droidsonroids.gif.n.a(Unknown Source)
        at pl.droidsonroids.gif.n.<init>(Unknown Source)
        at pl.droidsonroids.gif.f.<init>(Unknown Source)
        at pl.droidsonroids.gif.f.<init>(Unknown Source)
        at pl.droidsonroids.gif.aa.a(Unknown Source)
        at pl.droidsonroids.gif.ab.a(Unknown Source)
        at pl.droidsonroids.gif.ab.<init>(Unknown Source)
        at pl.droidsonroids.gif.aa.a(Unknown Source)
        at pl.droidsonroids.gif.GifImageView.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:883) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:886) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:522) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at android.support.v7.app.AppCompatDelegateImpl.b(Unknown Source) 
        at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source) 
        at com.xcaliber.mobilediagnostic.app.CosmeticConditionTest.onCreate(Unknown Source) 
        at android.app.Activity.performCreate(Activity.java:6845) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) `

tried every thing ,working in debug properly

**Comment by koral--** [comment]
> java.lang.UnsatisfiedLinkError: No implementation found for int pl.droidsonroids.gif.n.a(java.io.FileDescriptor) 

It seems that you are obfuscating native methods. Look here for the solution: https://github.com/koral--/android-gif-drawable/issues/623#issuecomment-447572590
