### ISSUE TITLE
oom

### ISSUE THREAD

**Issue by moujunqiang** [koral--/android-gif-drawable#632]
Caused by: java.lang.OutOfMemoryError

    at android.graphics.Bitmap.nativeCreate(Native Method)

    at android.graphics.Bitmap.createBitmap(Bitmap.java:810)

    at android.graphics.Bitmap.createBitmap(Bitmap.java:787)

    at android.graphics.Bitmap.createBitmap(Bitmap.java:754)

    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:229)

    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:160)

    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:95)

    at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:53)

    at pl.droidsonroids.gif.GifViewUtils.getResourceId(GifViewUtils.java:41)

    at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:30)

**Comment by koral--** [comment]
If you are trying to load large GIFs you may want do use subsampling like in sample project: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/sources/GifSourcesAdapter.kt#L39
