### ISSUE TITLE
ava.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libpl_droidsonroids_gif.so1.2.15" (built with --hash-style=gnu?)

### ISSUE THREAD

**Issue by cfJand** [koral--/android-gif-drawable#633]
Hello, My App has used the android-gif-drawable, but sometimes following Exception occurs:
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libpl_droidsonroids_gif.so1.2.15" (built with --hash-style=gnu?)
    at java.lang.Runtime.load(Runtime.java:331)
    at java.lang.System.load(System.java:982)
    at pl.droidsonroids.gif.ReLinker.loadLibrary(ReLinker.java:59)
    at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:50)
    at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:25)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:158)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:158)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:93)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:93)

And, I can't reappear this crash, it reported by the VIvo device android 5.02

**Comment by koral--** [comment]
Looks like device-specific issue. There are no additional linker options specified when building this library.
Does this issue happen for single user only?

**Comment by koral--** [comment]
Closing due to inactivity, may be reopened if more info is provided.

**Comment by currydou** [comment]
坚果pro 7.1.1  （in pixel 7.1.1 is ok.   ） 
But a new app in 坚果 is ok .

Caused by: java.lang.ExceptionInInitializerError
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:159)
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:94)
        at pl.droidsonroids.gif.GifTextView.getGifOrDefaultDrawable(GifTextView.java:141)
        at pl.droidsonroids.gif.GifTextView.init(GifTextView.java:90)
        at pl.droidsonroids.gif.GifTextView.<init>(GifTextView.java:46)
        	... 58 more
     Caused by: java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file
        at pl.droidsonroids.gif.ReLinker.unpackLibrary(ReLinker.java:101)
        at pl.droidsonroids.gif.ReLinker.loadLibrary(ReLinker.java:58)
        at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:51)
        at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
        	... 63 more
