### ISSUE TITLE
Caused by: java.lang.RuntimeException: Unlock pixels error, JNI exception

### ISSUE THREAD

**Issue by jiyewushen** [koral--/android-gif-drawable#635]
android:4.3 
version:1.2.15
phone:SM-N7502
```
//use code
GifDecoder mGifDecoder=new GifDecoder(inputSource);
        Bitmap buffer=Bitmap.createBitmap(mGifDecoder.getWidth(), mGifDecoder.getHeight(),
                Bitmap.Config.ARGB_4444);
        mGifDecoder.seekToFrame(0,buffer);
```
```java
Caused by: java.lang.RuntimeException: Unlock pixels error, JNI exception
    at pl.droidsonroids.gif.GifInfoHandle.seekToFrame(Native Method)
    at pl.droidsonroids.gif.GifInfoHandle.b(GifInfoHandle.java:278)
    at pl.droidsonroids.gif.c.b(GifDecoder.java:91)
```

**Comment by koral--** [comment]
`Config.ARGB_4444` won't work. Only `Config.ARGB_8888` is supported.

However, I can add more descriptive error message for such case.

**Comment by jiyewushen** [comment]
thank you very much!
