### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/5488dc38-a612-4535-af81-7ca7e4875ce0/user/0/com.my_app/app_lib/libpl_droidsonroids_gif.so1.2.16" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by gauravg2606** [koral--/android-gif-drawable#649]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/5488dc38-a612-4535-af81-7ca7e4875ce0/user/0/com.my_app/app_lib/libpl_droidsonroids_gif.so1.2.16" is 32-bit instead of 64-bit
       at java.lang.Runtime.load(Runtime.java:332)
       at java.lang.System.load(System.java:1069)
       at pl.droidsonroids.gif.ReLinker.loadLibrary(ReLinker.java:59)
       at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:51)
       at pl.droidsonroids.gif.GifInfoHandle.(SourceFile:27)
       at pl.droidsonroids.gif.GifDrawable.(SourceFile:123)
       at pl.droidsonroids.gif.GifDrawable.(SourceFile:134)

facing this crash in my app randomly, earlier I was also facing the same, then i tried with upgrading the lib version to 1.2.16 but still facing

**Comment by koral--** [comment]
It looks like https://github.com/koral--/android-gif-drawable/issues/636
Could add more info (especially how to reproduce this issue) there?
