### ISSUE TITLE
1.2.16  ClassNotFoundException when unmarshalling: pl.droidsonroids.gif.GifViewSavedState

### ISSUE THREAD

**Issue by extfff** [koral--/android-gif-drawable#659]
2009-01-01 05:57:10.290 29406-29406/xxxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxxx, PID: 29406
    java.lang.RuntimeException: Unable to start activity ComponentInfoxxxx/xxxx.ui.activity.Launcher}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: pl.droidsonroids.gif.GifViewSavedState
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:839)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: pl.droidsonroids.gif.GifViewSavedState
        at android.os.Parcel.readParcelableCreator(Parcel.java:2916)
        at android.os.Parcel.readParcelable(Parcel.java:2842)
        at android.os.Parcel.readValue(Parcel.java:2745)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3195)
        at android.os.Parcel.readSparseArray(Parcel.java:2407)
        at android.os.Parcel.readValue(Parcel.java:2802)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3114)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
        at android.os.BaseBundle.unparcel(BaseBundle.java:226)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1009)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2129)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1102)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1057)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1260)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:839)

**Comment by koral--** [comment]
Are you using proguard or R8 optimizations?

**Comment by Carlos2927** [comment]
R8

**Comment by koral--** [comment]
Closing due to inactivity. May be reopened if more info is provided.
