### ISSUE TITLE
Crash on ApkLibraryInstaller.java line 128

### ISSUE THREAD

**Issue by PraveenSheroes** [koral--/android-gif-drawable#666]
android.view.InflateException: Binary XML file line #83: Binary XML file line #83: Error inflating class pl.droidsonroids.gif.GifTextView

Note: Mostly Crash on  VIVO mobile phones

**Comment by koral--** [comment]
Could you attach complete stacktrace?

**Comment by koral--** [comment]
Closing due to inactivity.

**Comment by abahl817** [comment]
@koral-- 
Fatal Exception: java.lang.ExceptionInInitializerError
       at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:159)
       at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:94)
       at com.edurev.activity.SplashActivity.onCreate(SplashActivity.java:170)
       at android.app.Activity.performCreate(Activity.java:5322)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$900(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by com.getkeepsafe.relinker.MissingLibraryException: libpl_droidsonroids_gif.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
       at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
       at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:159)
       at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:94)
       at com.edurev.activity.SplashActivity.onCreate(SplashActivity.java:170)
       at android.app.Activity.performCreate(Activity.java:5322)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$900(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by koral--** [comment]
Are you using ABI splits, app bundles or have extractNativeLibs set in manifest?

**Comment by abahl817** [comment]
Yes I do use ABI splits.

**Comment by fouadkada** [comment]
No sure if related but Im facing a similar issue that only started to appear when I migrated my project to androidx

```
2019-11-24 14:08:39.069 17071-17071/com.example.mobile.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mobile.android, PID: 17071
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mobile.android/com.example.android.screens.splash.SplashActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
     Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.example.android.screens.splash.SplashActivity.onCreate(SplashActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ExceptionInInitializerError
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161)
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96)
        at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:55)
        at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.getResourceId(GifViewUtils.java:138)
        at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.<init>(GifViewUtils.java:124)
        at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:29)
        at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:41)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at com.example.android.screens.splash.SplashActivity.onCreate(SplashActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: pl.droidsonroids.relinker.MissingLibraryException: libpl_droidsonroids_gif.so
        at pl.droidsonroids.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
2019-11-24 14:08:39.069 17071-17071/com.example.mobile.android E/AndroidRuntime:     at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
        at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
        	... 33 more

```

**Comment by koral--** [comment]
This exception may only occur if normal library loading has failed and then fallback procedure has also failed.
The only possible solution I'm aware of is to use `android:extractNativeLibs="false"` in manifest. Look here for possible side-effects: https://stackoverflow.com/a/44704840/630398

However, if someone finds another solution, I'll review it.

**Comment by fouadkada** [comment]
In my case after cleaning the project and rebuilding, the problem seems to have gone
