### ISSUE TITLE
Out Of Memory Reported on firebase crash report while loading gif

### ISSUE THREAD

**Issue by FazalHussain** [koral--/android-gif-drawable#693]
I am facing out of memory on loading gif here is the stack trace of the crash reported by firebase

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 4194316 byte allocation with 1646992 free bytes and 1608KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1179)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:770)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
       at android.content.res.Resources.loadDrawable(Resources.java:1727)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:945)
       at android.widget.ImageView.<init>(ImageView.java:157)
       at android.widget.ImageView.<init>(ImageView.java:145)
       at android.widget.ImageView.<init>(ImageView.java:141)
       at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:40)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at com.mallconnect.tdm.main.storeDetail.StoreDetail.onCreateView(StoreDetail.java:126)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1460)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1852)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2625)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:2273)
       at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:733)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
```

I am trying to load gif like this
```

<pl.droidsonroids.gif.GifImageView
        android:id="@+id/map_loader"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:layout_gravity="center"
        android:src="@drawable/loading"
        android:visibility="gone" />
```

**Comment by koral--** [comment]
`4194316 byte` it looks like big file.
You can try to subsample it.
Here is an example: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/sources/GifSourcesAdapter.kt#L39

**Comment by FazalHussain** [comment]
The file is of 571KB. The loading gif is showing in the majority of screens I think there is some recycling issue. Is there any property for recycle before setting the gif in XML?

**Comment by koral--** [comment]
There is no such property.
Could you share a minimal sample project which reproduces this issue?
