### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by XingSpace** [koral--/android-gif-drawable#705]
Hi,koral. I got this error .And my Gradle version is `'com.android.tools.build:gradle:3.4.1'`,

the gif-drawable version is `'pl.droidsonroids.gif:android-gif-drawable:1.2.19'`

`java.lang.ExceptionInInitializerError
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:125)
        at com.azld.digitalplayer.component.MyPicView.drawView(MyPicView.java:115)
        at com.azld.digitalplayer.component.BaseComponent.<init>(BaseComponent.java:40)
        at com.azld.digitalplayer.component.MyPicView.<init>(MyPicView.java:53)
        at com.azld.digitalplayer.view.MediaIntegrationViewAdaptor.createPicView(MediaIntegrationViewAdaptor.java:994)
        at com.azld.digitalplayer.view.MediaIntegrationViewAdaptor.instantiateItem(MediaIntegrationViewAdaptor.java:247)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1005)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1219)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1087)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1613)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChild(ViewGroup.java:6805)
        at android.view.ViewGroup.measureChildren(ViewGroup.java:6782)
        at android.widget.AbsoluteLayout.onMeasure(AbsoluteLayout.java:66)
        at android.view.View.measure(View.java:23466)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: pl.droidsonroids.relinker.MissingLibraryException: libpl_droidsonroids_gif.so
        at pl.droidsonroids.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:70)
2019-10-30 16:06:06.409 15744-15744/com.azld.digitalplayer E/AZLD:     at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
        at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
        	... 52 more`

**Comment by koral--** [comment]
It looks similar to https://github.com/koral--/android-gif-drawable/issues/666, let's continue there.
