### ISSUE TITLE
Cant compile CMakeLists.txt

### ISSUE THREAD

**Issue by baptistapedro** [koral--/android-gif-drawable#711]
Hello,
I'm trying to compile the CMakeLists.txt but I'm having a hard time, please follow here https://dpaste.de/OsHZ/raw

It creates the CMakeFiles and also generate the .o files like `init.c.o` however I'm not able to link those into my own file.c

What's wrong with the compilation?

**Comment by koral--** [comment]
`-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/libs/armeabi-v7a`
Does this directory exist? Path is absolute, starting from /, which is quite unusual.

**Comment by baptistapedro** [comment]
Koral,
I tried =libs/armeabi-v7a
I already tried to remove the output dir flag as well, and the issue is the same.

Can you descrbie step by step  how to compile it with cmake?

Just an example, I tried to link one of the .o files, check the error I'm having:

```
clang -g -O1 -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux CMakeFiles/pl_droidsonroids_gif.dir/init.c.o myf.c -o myf
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
/usr/bin/ld: CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: Relocations in generic ELF (EM: 40)
CMakeFiles/pl_droidsonroids_gif.dir/init.c.o: error adding symbols: File in wrong format
```

**Comment by koral--** [comment]
Here is what is invoked by Gradle:
```Executable : /opt/android-sdk-update-manager/cmake/3.6.4111459/bin/cmake
arguments : 
-Hprojects/android-gif-drawable/android-gif-drawable/src/main/c
-Bprojects/android-gif-drawable/android-gif-drawable/.cxx/cmake/debug/x86_64
-DANDROID_ABI=x86_64
-DANDROID_PLATFORM=android-17
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=projects/android-gif-drawable/android-gif-drawable/build/intermediates/cmake/debug/obj/x86_64
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=/opt/android-sdk-update-manager/ndk/20.0.5594570
-DCMAKE_C_FLAGS=-std=c11 -Weverything -Wall -DDEBUG -g
-DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk-update-manager/ndk/20.0.5594570/build/cmake/android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=/opt/android-sdk-update-manager/cmake/3.6.4111459/bin/ninja
-GAndroid Gradle - Ninja
-DANDROID_PLATFORM=android-17
-DANDROID_STL=none
jvmArgs : 

```

**Comment by baptistapedro** [comment]
Lemme confirm, are these the flags to pass to the cmake cmdline right?

**Comment by koral--** [comment]
Yes, exactly.

**Comment by baptistapedro** [comment]
I have the android NDK (android-ndk-r20b) the latest one and it does not contain the /bin/ninja binary, so I excluded that flag and remained with everything else as follows:

```
cmake -Hprojects/android-gif-drawable/android-gif-drawable/src/main/c -Bprojects/android-gif-drawable/android-gif-drawable/.cxx/cmake/debug/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-17 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=projects/android-gif-drawable/android-gif-drawable/build/intermediates/cmake/debug/obj/x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=~/android-ndk-r20b -DCMAKE_C_FLAGS=-std=c11 -Weverything -Wall -DDEBUG -g -DCMAKE_TOOLCHAIN_FILE=~/android-ndk-r20b/build/cmake/android.toolchain.cmake -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-17 -DANDROID_STL=none
CMake Error: Could not create named generator Android

```

You can see the error I have and probably has nothing to do with the lack of the ninja flag?

**Comment by koral--** [comment]
I don't use cmake directly, so this is only a blind suggestion:
could you try quoting parameters containing spaces?

**Comment by baptistapedro** [comment]
That does not change the output.

**Comment by baptistapedro** [comment]
Well you have a CMakeLists.txt so you might compiled somehow.
Do you mind to try on your machine please?

**Comment by koral--** [comment]
It is referenced here: https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/build.gradle#L36 and configured here: https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/build.gradle#L22
I compile it using Gradle and its external native builds: https://developer.android.com/studio/projects/gradle-external-native-builds

**Comment by baptistapedro** [comment]
as long as I'm able to generate the .o files and possible the all .so files (not only the main .so file that is used as /lib for android apps).
I never used gradle to build projects but I gave it a try perhaps you can tell me what's the correct way to do it with gradle, I gave it a try, check out: https://dpaste.de/O6k2/raw

**Comment by baptistapedro** [comment]
------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2016-01-26 15:17:49 UTC
Build number: none
Revision:     UNKNOWN

Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 20 2018
JVM:          1.8.0_222 (Private Build 25.222-b10)
OS:           Linux 4.15.0-70-generic amd64

**Comment by koral--** [comment]
Gradle 2.10 is very very old, that's why it does not recognize `google()` repo. The newest stable version is 6.

**Comment by baptistapedro** [comment]
I tried the latest version and 5.6.2, because seems the project was built with it.
----
~/Desktop/gradle-5.6.2/bin/gradle build.gradle droidson

FAILURE: Build failed with an exception.

* What went wrong:
Task 'build.gradle' not found in root project 'android-gif-drawable'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by baptistapedro** [comment]
please post the exact commands I should use

**Comment by baptistapedro** [comment]
I did `gradle -q archieveSymbols`
then I noticed this path
```
nasa@ubuntu:~/android-gif-drawable/android-gif-drawable/build/libs$ ls -al
total 60
drwxrwxr-x 2 nasa nasa  4096 Dec  2 06:27 .
drwxrwxr-x 4 nasa nasa  4096 Dec  2 06:27 ..
-rw-rw-r-- 1 nasa nasa   261 Dec  2 06:27 android-gif-drawable-1.2.20-SNAPSHOT-javadoc.jar
-rw-rw-r-- 1 nasa nasa 47364 Dec  2 06:27 android-gif-drawable-1.2.20-SNAPSHOT-sources.jar
```

the .c files on src/main/c, were not compiled though

**Comment by koral--** [comment]
You can invoke `./gradlew build` (`gradlew` is located in project root directory).

**Comment by baptistapedro** [comment]
> Task :android-gif-drawable:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':android-gif-drawable:lint'.
> No value has been specified for property 'lintClassPath'.

**Comment by koral--** [comment]
It seems that something is wrong with your environment. Impossible to say what with that amount of logs.

**Comment by baptistapedro** [comment]
```
nasa@ubuntu:~/android-gif-drawable$ ./gradlew build --stacktrace
> Task :android-gif-drawable:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':android-gif-drawable:lint'.
> No value has been specified for property 'lintClassPath'.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':android-gif-drawable:lint'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:72)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:178)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:154)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:41)
        at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:40)
        at org.gradle.execution.DefaultBuildWorkExecutor.access$000(DefaultBuildWorkExecutor.java:24)
        at org.gradle.execution.DefaultBuildWorkExecutor$1.proceed(DefaultBuildWorkExecutor.java:48)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
        at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:40)
        at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:33)
        at org.gradle.execution.IncludedBuildLifecycleBuildWorkExecutor.execute(IncludedBuildLifecycleBuildWorkExecutor.java:36)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.run(BuildOperationFiringBuildWorkerExecutor.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:41)
        at org.gradle.initialization.DefaultGradleLauncher.runWork(DefaultGradleLauncher.java:236)
        at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:147)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:126)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:106)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:60)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:57)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:85)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'lintClassPath'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:69)
        ... 128 more


```

**Comment by baptistapedro** [comment]
Hey @koral-- 
You were right my environment wasn't okay, I got it fixed already.
Now I'm having ninja errors while compiling the files. I feel that it's almost there!...

Please gimme your thoughts on this error https://dpaste.de/9CH1/raw

**Comment by Taolaw** [comment]
some error occured, build log:
```bash
luna@luna-ubuntu:~/Downloads/android-gif-drawable-dev$ ./gradlew build
> Task :android-gif-drawable:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':android-gif-drawable:lint'.
> No value has been specified for property 'lintClassPath'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 766ms
3 actionable tasks: 1 executed, 2 up-to-date
```
