### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c5c4510

### ISSUE THREAD

**Issue by amazingokc** [koral--/android-gif-drawable#741]
The version I'm using is 1.2.17.

java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c5c4510
    at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:69)
    at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:164)
    at android.graphics.Canvas.drawBitmap(Canvas.java:1598)
    at pl.droidsonroids.gif.GifDrawable.draw(GifDrawable.java:784)
    at android.widget.ImageView.onDraw(ImageView.java:1470)
    at android.view.View.draw(View.java:22234)
    at android.view.View.draw(View.java:22103)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22237)
    at android.view.View.draw(View.java:22103)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22101)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4520)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4257)
    at android.view.View.draw(View.java:22237)
    at com.android.internal.policy.DecorView.draw(DecorView.java:872)
    at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4257)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4161)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3851)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3102)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2002)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8358)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1093)
    at android.view.Choreographer.doCallbacks(Choreographer.java:916)
    at android.view.Choreographer.doFrame(Choreographer.java:843)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:238)
    at android.app.ActivityThread.main(ActivityThread.java:7880)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

**Comment by koral--** [comment]
Please post your code which reproduces this issue.

**Comment by koral--** [comment]
Closing due to inactivity
