### ISSUE TITLE
MissingLibraryException

### ISSUE THREAD

**Issue by Citrussss** [koral--/android-gif-drawable#760]
ndk {
            abiFilters 'arm64-v8a'
            abiFilters 'armeabi'
        }

device:vivo-y55 (armeabi-v7a) 
version:1.2.21
info:
Caused by: java.lang.ExceptionInInitializerError
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96)
    at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:55)
    at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.getResourceId(GifViewUtils.java:138)
    at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.<init>(GifViewUtils.java:124)
    at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:29)
    at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:41)
    at java.lang.reflect.Constructor.newInstance(Native Method) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:628) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:809) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
    at org.c2h4.afei.beauty.homemodule.fragment.MainHomeFragment$3.onSuccess(MainHomeFragment.java:723) 
    at org.c2h4.afei.beauty.homemodule.fragment.MainHomeFragment$3.onSuccess(MainHomeFragment.java:705) 
    at org.c2h4.afei.beauty.homemodule.datasource.HomeDataSource$6.onSuccess(HomeDataSource.java:211) 
    at com.lzy.okgo.cache.policy.NoCachePolicy$1.run(NoCachePolicy.java:43) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5563) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
 Caused by: pl.droidsonroids.relinker.MissingLibraryException: libpl_droidsonroids_gif.so
    at pl.droidsonroids.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
    at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
    at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
    at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:70)
    at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:51)
    at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
    at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161) 
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96) 
    at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:55) 
    at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.getResourceId(GifViewUtils.java:138) 
    at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.<init>(GifViewUtils.java:124) 
    at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:29) 
    at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:41) 
    at java.lang.reflect.Constructor.newInstance(Native Method) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:628) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:809) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
    at org.c2h4.afei.beauty.homemodule.fragment.MainHomeFragment$3.onSuccess(MainHomeFragment.java:723) 
    at org.c2h4.afei.beauty.homemodule.fragment.MainHomeFragment$3.onSuccess(MainHomeFragment.java:705) 
    at org.c2h4.afei.beauty.homemodule.datasource.HomeDataSource$6.onSuccess(HomeDataSource.java:211) 
    at com.lzy.okgo.cache.policy.NoCachePolicy$1.run(NoCachePolicy.java:43) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5563) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by Citrussss** [comment]
i guess lost armeabi.so?

**Comment by koral--** [comment]
armeabi is not present in artifacts for a long time. It is not supported by NDK r17 and newer.
You have to use `abiFilters 'armeabi-v7a'` for 32-bit ARM.
