### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/user_de/0/com.android.settings/app_lib/libpl_droidsonroids_gif.so" segment 0: Permission denied

### ISSUE THREAD

**Issue by JsonNan** [koral--/android-gif-drawable#775]
java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/user_de/0/com.android.settings/app_lib/libpl_droidsonroids_gif.so" segment 0: Permission denied
        at java.lang.Runtime.load0(Runtime.java:939)
        at java.lang.System.load(System.java:1628)
        at pl.droidsonroids.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
        at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161)
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96)
        at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:55)
        at pl.droidsonroids.gif.GifImageView.setImageResource(GifImageView.java:101)

What causes this and how to solve it?

**Comment by koral--** [comment]
What is the device model and Android version?

**Comment by privateAss** [comment]
version：Android 7.0,level 24
model：BZA-L00

**Comment by koral--** [comment]
Are you using app bundles? If so it may be the same issue as https://issuetracker.google.com/issues/127691101
Workaround is to add `android.bundle.enableUncompressedNativeLibs=false` property,

**Comment by koral--** [comment]
Closing due to inactivity
