### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by daogepiqian** [koral--/android-gif-drawable#786]
versio 'pl.droidsonroids.gif:android-gif-drawable:1.2.+'

2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err: pl.droidsonroids.gif.GifIOException: GifError 101: Failed to open given input: Bad file descriptor
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at pl.droidsonroids.gif.GifInfoHandle.extractNativeFileDescriptor(Native Method)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at pl.droidsonroids.gif.GifInfoHandle.openFileDescriptor(GifInfoHandle.java:83)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at pl.droidsonroids.gif.GifInfoHandle.<init>(GifInfoHandle.java:40)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:172)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.task.DefaultImageLoaderTask.decodeGif(DefaultImageLoaderTask.java:480)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.task.DefaultImageLoaderTask.onDecodeStream(DefaultImageLoaderTask.java:202)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.task.DefaultImageLoaderTask.decodeStream(DefaultImageLoaderTask.java:80)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.ImageFetcher.decodeStream(ImageFetcher.java:75)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.ImageWorker$BitmapWorkerTask.doInBackgroundForStream(ImageWorker.java:656)
2021-12-02 13:45:27.494 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.ImageWorker$BitmapWorkerTask.doInBackground(ImageWorker.java:580)
2021-12-02 13:45:27.495 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.ImageWorker$BitmapWorkerTask.doInBackground(ImageWorker.java:530)
2021-12-02 13:45:27.495 2018-2443/com.shuqi.controller W/System.err:     at com.aliwx.android.core.imageloader.AsyncTask$2.call(AsyncTask.java:314)
2021-12-02 13:45:27.495 2018-2443/com.shuqi.controller W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2021-12-02 13:45:27.495 2018-2443/com.shuqi.controller W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2021-12-02 13:45:27.495 2018-2443/com.shuqi.controller W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2021-12-02 13:45:27.495 2018-2443/com.shuqi.controller W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by koral--** [comment]
Please attach a code snippet reproducing this issue.

**Comment by koral--** [comment]
Closing due to inactivity
