### ISSUE TITLE
android.graphics.drawable.BitmapDrawable cannot be cast to pl.droidsonroids.gif.b Exception

### ISSUE THREAD

**Issue by IRonMaxTech** [koral--/android-gif-drawable#794]
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {scooltr/com.example.scooltr.MainChooserActivity}: java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to pl.droidsonroids.gif.b
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3138)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by koral--** [comment]
You have to post a code reproducing this issue.

**Comment by koral--** [comment]
Closing due to inactivity

**Comment by KananTaghili** [comment]
May be image resource is not .gif file, .png can not cast to GifDrawable
