### ISSUE TITLE
 Caused by: pl.droidsonroids.relinker.MissingLibraryException: Could not find 'libpl_droidsonroids_gif.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

### ISSUE THREAD

**Issue by hockgod520** [koral--/android-gif-drawable#796]
VivoS10 - V2121A Android 11 
Caused by: pl.droidsonroids.relinker.MissingLibraryException: Could not find 'libpl_droidsonroids_gif.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
        at pl.droidsonroids.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
        at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161) 
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96) 
        at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:55) 
        at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.getResourceId(GifViewUtils.java:138) 
        at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.<init>(GifViewUtils.java:124) 
        at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:29) 
        at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:41) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:873) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1061) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1178) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1139) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1181) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1139) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1181) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1139) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:696) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:548) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at com.lefu.weguardhome.ui.widget.ScalePopupWindow.<init>(ScalePopupWindow.java:108) 
        at com.lefu.weguardhome.ui.activity.MainActivity.initPopWindow(MainActivity.java:320) 
        at com.lefu.weguardhome.ui.activity.MainActivity.initLanguage(MainActivity.java:269) 
        at com.lefu.weguardhome.ui.activity.MainActivity.initView(MainActivity.java:246) 
        at com.lefu.weguardhome.base.BaseActivity.onCreate(BaseActivity.java:101) 
        at android.app.Activity.performCreate(Activity.java:8137) 
        at android.app.Activity.performCreate(Activity.java:8121) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3748) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161) 
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96) 
        at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:55) 
        at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.getResourceId(GifViewUtils.java:138) 
        at pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.<init>(GifViewUtils.java:124) 
        at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:29) 
        at pl.droidsonroids.gif.GifImageView.<init>(GifImageView.java:41)

**Comment by hockgod520** [comment]
ndk\21.1.6352462   ----------ndk\21.1.6352462

**Comment by hockgod520** [comment]
It's an NDK version problem
