### ISSUE TITLE
   java.lang.ExceptionInInitializerError         at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:158)         at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:93)

### ISSUE THREAD

**Issue by binbinyYang** [koral--/android-gif-drawable#807]
hi ,A mobile phone will report an error， Thank You

Use:   1.android-gif-drawable-1.2.15.aar
          2.glide.jar (4.0+)

 Process: com.android.systemui, PID: 31415
    java.lang.ExceptionInInitializerError
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:158)
        at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:93)
        at com.xlw.systemui.navi.car.item.NaviOptionItem.updateView(NaviOptionItem.java:64)
        at com.xlw.systemui.navi.car.viewholder.NaviViewHolder.update(NaviViewHolder.java:20)
        at com.xlw.systemui.navi.car.NaviItemAdapter.onBindViewHolder(NaviItemAdapter.java:63)
        at com.xlw.systemui.navi.car.NaviItemAdapter.onBindViewHolder(NaviItemAdapter.java:20)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7031)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7073)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5990)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6257)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6096)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6092)
        at com.xlw.systemui.qs.car.recyclerview.SpannedGridLayoutManager.layoutRow(SpannedGridLayoutManager.java:463)
        at com.xlw.systemui.qs.car.recyclerview.SpannedGridLayoutManager.onLayoutChildren(SpannedGridLayoutManager.java:144)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3521)
        at android.view.View.measure(View.java:24545)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
        at android.view.View.measure(View.java:24545)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24545)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24545)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
        at android.view.View.measure(View.java:24545)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3006)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1833)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2122)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file

**Comment by koral--** [comment]
>  Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file

Are you using ABI splits or ABI filters in your build.gradle(.kts).

**Comment by binbinyYang** [comment]
no using, but  Later, I changed it do: Use: 1.android-gif-drawable-1.2.19.aar
2.glide.jar (4.0+)      
The above problems will not occur               so.why????

**Comment by koral--** [comment]
Please create and share a project with the minimum reproducible sample.

**Comment by binbinyYang** [comment]
hi  ！
I can't provide it, because my project is changed on the basis of Android 10 source code, and I do system application development

**Comment by koral--** [comment]
OK, so it will be difficult to help you.
The .so file of the supported ABI has to be available.
Check if it is present in the APK (unzip it). If it isn't you have a packaging issue.

**Comment by binbinyYang** [comment]
Good morning, thank you for your help,
