### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by FightingForDevelop** [koral--/android-gif-drawable#828]
my version is 1.2.18
java.lang.ExceptionInInitializerError
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:7)
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:1)
at ***.common.view.GifImageView.setImageResource(GifImageView.java:2)
at ***.activity.MainActivity.initViews(MainActivity.java:19)
at com.baidu.protect.A.V(Native Method)
at ***.activity.MainActivity.onCreate(MainActivity.java:3)
at android.app.Activity.performCreate(Activity.java:6701)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2651)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6197)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
Caused by: m.a.a.b: libpl_droidsonroids_gif.so
at pl.droidsonroids.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:39)
at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:15)
at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:5)
at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:2)
at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:1)
at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:2)
at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:1)
... 18 more

**Comment by koral--** [comment]
Does it happen also on the newest version? If so please share a complete reproducer project.

**Comment by FightingForDevelop** [comment]
> Does it happen also on the newest version? If so please share a complete reproducer project.

I haven't use the newest version,but this error always occur on Android 7.1.2.I see it just by Crash platform,I did not reproduce it on my 7.1.2 phone.

By the way, does GitDrawable support loading urls?

And can the libpl_droidsonroids_gif.so be deleted?

**Comment by koral--** [comment]
Sorry, but with this amount of information I cannot do anything.
I can only recommend you updating to the recent version. There were several improvements regarding native library loading.

You may also check `com.baidu.protect.A.V`. I don't know if it is a part of your code or it is some external library but it may interfere with library loading if it is in the stacktrace.

> By the way, does GitDrawable support loading urls?

Library itself - no. But, there is a sample: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt

> And can the libpl_droidsonroids_gif.so be deleted?

No. It is mandatory for library to work.

So, I'm closing this issue as there is no possible action to perform on my side.

**Comment by FightingForDevelop** [comment]
> Sorry, but with this amount of information I cannot do anything. I can only recommend you updating to the recent version. There were several improvements regarding native library loading.
> 
> You may also check `com.baidu.protect.A.V`. I don't know if it is a part of your code or it is some external library but it may interfere with library loading if it is in the stacktrace.
> 
> > By the way, does GitDrawable support loading urls?
> 
> Library itself - no. But, there is a sample: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt
> 
> > And can the libpl_droidsonroids_gif.so be deleted?
> 
> No. It is mandatory for library to work.
> 
> So, I'm closing this issue as there is no possible action to perform on my side.

OK,Do I need to import both  libpl_droidsonroids_gif.so and libpl_droidsonroids_gif_surface.so at the same time?
<img width="391" alt="image" src="https://github.com/koral--/android-gif-drawable/assets/21364504/bc0b1aea-b771-42fc-976a-de5ac854cbfb">

**Comment by koral--** [comment]
`libpl_droidsonroids_gif_surface` was used by this library in the past but has been removed a long time ago.
Earlier than `1.2.18`
`libpl_droidsonroids_gif` is the only file used now.
